#ifndef _EVENT_H_
#define _EVENT_H_

#include "types.h"

typedef struct VIEW_CLIP 
{
	// total size: 0xC
	char room;   // offset 0x0, size 0x1
	char rcase;  // offset 0x1, size 0x1
	char evc_no; // offset 0x2, size 0x1
	float near;  // offset 0x4, size 0x4
	float far;   // offset 0x8, size 0x4
} VIEW_CLIP;

void bhInitEvent();
void bhControlEvent();
unsigned int bhEnd();
unsigned int bhIfelCk();
unsigned int bhElseCk();
unsigned int bhEndif();
unsigned int dm0();
unsigned int bhCk();
unsigned int bhSet();
unsigned int bhCmpB();
unsigned int bhCmpW();
unsigned int bhSv();
unsigned int bhSvW();
unsigned int bhEvtOn();
unsigned int bhCamSet();
unsigned int bhCamSet2();
unsigned int bhCamPauseSet();
unsigned int bhMessageSet();
unsigned int bhBgmOn();
unsigned int bhBgmOff();
unsigned int bhSeOn();
unsigned int bhSeOff();
unsigned int bhBGSeOn();
unsigned int bhBGSeOff();
unsigned int bhUseItemCheck();
unsigned int bhArmsItemCheck();
unsigned int bhArmsItemChange();
unsigned int bhPlItemLost();
unsigned int bhUseItemClear();
unsigned int bhPlItemCheck();
unsigned int bhMovieStart();
unsigned int bhMovieStop();
unsigned int bhVoiceOn();
unsigned int bhVoiceOff();
unsigned int bhAdxCk();
unsigned int bhAdxTimeCk();
unsigned int bhCineSet();
unsigned int bhWalAtariSet();
unsigned int bhEtcAtariSet();
unsigned int bhFlrAtariSet();
unsigned int bhSubStatus();
unsigned int bhMotionPauseSet();
unsigned int bhMotionPauseSetPly();
unsigned int bhInitMotionPause();
unsigned int bhInitMotionPauseEx();
unsigned int bhEffectSet();
unsigned int bhEffectSensyaSet();
unsigned int bhEffectKokuenSet();
unsigned int bhDieCk();
unsigned int bhItmCk();
unsigned int bhObjLinkSet();
unsigned int bhSetObjMotion();
unsigned int bhSetDispObj();
unsigned int bhSetDoorCall();
unsigned int bhDieEventCk();
unsigned int bhSetDebugLoopEx();
unsigned int bhInitSetKage();
unsigned int bhObjLinkSetPly();
unsigned int bhSetNextRoomBgm();
unsigned int bhSetNextRoomBgSe();
unsigned int bhFootSeCall();
unsigned int bhEneSetCk();
unsigned int bhItmSetCk();
unsigned int bhInitModelSet();
unsigned int bhEtcAtariSet2();
unsigned int bhLightSet();
unsigned int bhWeaponSeCall();
unsigned int bhYakkyouSet();
unsigned int bhFadeSet();
unsigned int bhRoomCaseNo();
unsigned int bhFrameCheck();
unsigned int bhCamInfoSet();
unsigned int bhMaskSet();
unsigned int bhLipSet();
unsigned int bhMaskStart();
unsigned int bhLipStart();
unsigned int bhMutekiSetPl();
unsigned int bhLookGsetPlStart();
unsigned int bhLookGsetPlStop();
unsigned int bhSoundFadeOut();
unsigned int bhDefModelSet();
unsigned int bhItmAspdSet();
unsigned int bhEffDispSet();
unsigned int bhEffAmbSet();
unsigned int bhObjLinkSetObjEne();
unsigned int bhObjLinkSetObjItem();
unsigned int bhObjLinkSetEneItem();
unsigned int bhObjLinkSetEneEne();
unsigned int bhDelObjSe();
unsigned int bhLightTypeSet();
unsigned int bhFogColorSet();
unsigned int bhEffectSandSet();
unsigned int bhPlItemBlockCk();
unsigned int bhEffBloodSet();
unsigned int bhEffBloodPoolSet();
unsigned int bhEffBloodPoolSet2();
unsigned int bhCyoutenHenkeiSet();
unsigned int bhCyoutenHenkeiStart();
unsigned int bhFixEventCamPly();
unsigned int bhObjLinkSetObjObj();
unsigned int bhCamYureSet();
unsigned int bhInitCamSet();
unsigned int bhMesDispEndSet();
unsigned int bhPadCheck();
unsigned int bhTFrameCheck();
unsigned int bhEventTimerClr();
unsigned int bhCamCheck();
unsigned int bhRandamSet();
unsigned int bhEventSkipSet();
unsigned int bhDelYakkyou();
unsigned int bhObjAlphaSet();
unsigned int bhCyodanSet();
unsigned int bhHEffectSet();
unsigned int bhObjLinkSetObjPly();
unsigned int bhEffPush();
unsigned int bhEffPop();
unsigned int bhAreaSearchObj();
unsigned int bhLightParameterCSet();
unsigned int bhLightParameterStart();
unsigned int bhInitMidiSlotSet();
unsigned int bh3dSoundFlagSet();
unsigned int bhSoundVolumeSet();
unsigned int bhLightParameterSet();
unsigned int bhEneSeOn();
unsigned int bhEneSeOff();
unsigned int bhWalAtariSet2();
unsigned int bhFlrAtariSet2();
unsigned int bhMotionPosSetEnePly();
unsigned int bhKageSwSet();
unsigned int bhSoundPanSet();
unsigned int bhInitPonySet();
unsigned int bhCyoutenHenkeiSetEX();
unsigned int bhCyoutenHenkeiStartEX();
unsigned int bhEasySESet();
unsigned int bhSoundFlagReSet();
unsigned int bhEffUVSet();
unsigned int bhPlayerChangeSet();
unsigned int bhPlayerPoisonCk();
unsigned int bhAddObjSe();
unsigned int bhRandTest();
unsigned int bhEvtComSet();
unsigned int bhZombieUpDieCk();
unsigned int bhFacePauseSet();
unsigned int bhFaceReSet();
unsigned int bhEffModeSet();
unsigned int bhEnemyHpUp();
unsigned int bhFaceRep();
unsigned int bhBGSeOff2();
unsigned int bhBgmOff2();
unsigned int bhBGSeOn2();
unsigned int bhBgmOn2();
unsigned int bhMovieCk();
unsigned int bhSetItmMotion();
unsigned int bhObjAspdSet();
unsigned int bhPuruPuruFlagSet();
unsigned int bhPuruPuruStart();
unsigned int bhSubMapBusyCk();
unsigned int bhMapSystemOn();
unsigned int bhTrapDamageSet();
unsigned int bhEvtLighterFireSet();
unsigned int bhObjLinkSetPlyItem();
unsigned int bhPlayerKaidanMotion();
unsigned int bhEneRenderSet();
unsigned int bhBgmOnEx();
unsigned int bhBgmOn2Ex();
unsigned int bhFogParameterCSet();
unsigned int bhFogParameterStart();
unsigned int bhEffUVSet2();
unsigned int bhBGColorSet();
unsigned int bhMovieTimeCk();
unsigned int bhEffTypeSet();
unsigned int bhPlayerPoison2Cr();
unsigned int bhPlyHandChange();
unsigned int bhHEffectSet2();
unsigned int bhObjDposCk();
unsigned int bhItemGetGet();
unsigned int bhEtcAtariEnePosSet();
unsigned int bhEtcAtariEvtPosSet();
unsigned int bhRoomSoundCase();
unsigned int bhItemPlToSBox();
unsigned int bhItemSBoxToIBox();
unsigned int bhGrdPosSet();
unsigned int bhGrdPosMoveCSet();
unsigned int bhGrdPosMoveStart();
unsigned int bhEvtKill();
unsigned int bhReTryPointSet();
unsigned int bhPlyDposCk();
unsigned int bhPlItemLostEx();
unsigned int bhCyodanSetEx();
unsigned int bhArmsItemSet();
unsigned int bhItemGetGetEx();
unsigned int bhEffectSandSetMatsumoto();
unsigned int bhVoiceWait();
unsigned int bhVoiceStart();
unsigned int bhGameOverSet();
unsigned int bhPlItemChangeM();
unsigned int bhEffBakuDrmSet();
unsigned int bhPlItemTamaSet();
unsigned int bhEffClearEvt();
unsigned int bhEvtTimerSet();
unsigned int bhEneLookFlgSet();
unsigned int bhReturnTitleEvt();
unsigned int bhSyukanModeSet();
unsigned int bhExGameItemInit();
unsigned int bhEneLifeSetM();
unsigned int bhEffSSizeSet();
unsigned int bhEffLinkOffsetSet();
unsigned int bhRankingCall();
unsigned int bhCallSysSe();
unsigned int bhSleep();
unsigned int bhSleeping();
unsigned int bhWhile();
unsigned int bhEwhile();
unsigned int bhEwhile2();
unsigned int bhEvtNext();
unsigned int bhComNext();
unsigned int bhEvtEnd();
unsigned int bhFor();
unsigned int bhNext();
unsigned int bhPlCtr();
int Player_controll();
unsigned int bhObjCtr();
int Obj_controll();
unsigned int bhSubCtr();
int Sub_controll();
unsigned int bhCommonCtr();
int Common_controll();
unsigned int bhLoadWork();
unsigned int bhLoadWorkEx();
unsigned int bhLoadWork2();
int Event_init(BH_SCEWORK* a0, unsigned int evt_id);
int Event_exec(unsigned int task_level, unsigned int evt_id);
int bhEventScheduler2();
void bhScenarioCheck(unsigned char* next_ptr);
unsigned int bhFlagCk(unsigned char type, unsigned int cnt, unsigned char flag);
unsigned int bhFlagSet(unsigned char type, unsigned int cnt, unsigned char flag);
void bhChangeViewClip(char stg_no, char rom_no, char rcase, int evc_no);
void bhChangeViewClipRM();
void bhChangeClipVolume(char stg_no, char rom_no, char rcase, int evc_no);
void bhChangeClipVolumeRM();

extern float GameFar;
extern float GameNear;

#endif
